options(digits=17)
script <- sub("^--file=","",grep("^--file=",commandArgs(),value=TRUE)[1])
P <- normalizePath(file.path(dirname(script),".."),winslash="/")
for (f in c("figures","expected")) dir.create(file.path(P,f),showWarnings=FALSE)
d <- read.csv(file.path(P,"data/tea.csv"),stringsAsFactors=FALSE)
stopifnot(!anyNA(d))
counts <- table(factor(d$correct_milk,levels=0:4))
stopifnot(nrow(d)==70,all(as.integer(counts)==c(1,16,36,16,1)))
m <- c(n=nrow(d),p_all=mean(d$correct_milk>=4),p_at_least_three=mean(d$correct_milk>=3))
draw <- function() barplot(counts,xlab="Correct milk-first cups",ylab="Number of allocations",main="Null randomization: 70 allocations")
write.csv(data.frame(metric=names(m),value=as.numeric(m)),file.path(P,"expected/r.csv"),row.names=FALSE)
png(file.path(P,"figures/result-r.png"),width=1024,height=672,res=160)
draw()
invisible(dev.off())
print(m)
