options(digits=17)
script <- sub("^--file=","",grep("^--file=",commandArgs(),value=TRUE)[1])
P <- normalizePath(file.path(dirname(script),".."),winslash="/")
for (f in c("figures","expected")) dir.create(file.path(P,f),showWarnings=FALSE)
d <- read.csv(file.path(P,"data/titanic.csv"),stringsAsFactors=FALSE)
stopifnot(!anyNA(d))
stopifnot(nrow(d)==32,sum(d$Freq)==2201)
t <- xtabs(Freq~Sex+Survived,data=d)
pm <- t["Male","Yes"]/sum(t["Male",]);pf <- t["Female","Yes"]/sum(t["Female",])
d$Sex <- factor(d$Sex,levels=c("Male","Female"))
fit <- glm(I(Survived=="Yes")~Sex,weights=Freq,family=binomial(),data=d)
tp <- t["Female","Yes"];fp <- t["Female","No"];tn <- t["Male","No"];fn <- t["Male","Yes"]
m <- c(n=sum(d$Freq),survived=sum(t[,"Yes"]),p_male=pm,p_female=pf,intercept_male=unname(coef(fit)[1]),coef_female=unname(coef(fit)[2]),TP=tp,FP=fp,TN=tn,FN=fn,sensitivity=tp/(tp+fn),specificity=tn/(tn+fp),accuracy=(tp+tn)/2201,auc=(tp/(tp+fn)+tn/(tn+fp))/2)
draw <- function() barplot(c(Male=pm,Female=pf),ylim=c(0,1),ylab="Observed survival proportion",main="Historical aggregate; not causation")
write.csv(data.frame(metric=names(m),value=as.numeric(m)),file.path(P,"expected/r.csv"),row.names=FALSE)
png(file.path(P,"figures/result-r.png"),width=1024,height=672,res=160)
draw()
invisible(dev.off())
print(m)
