options(digits=17)
script <- sub("^--file=","",grep("^--file=",commandArgs(),value=TRUE)[1])
P <- normalizePath(file.path(dirname(script),".."),winslash="/")
for (f in c("figures","expected")) dir.create(file.path(P,f),showWarnings=FALSE)
d <- read.csv(file.path(P,"data/mtcars.csv"),stringsAsFactors=FALSE)
stopifnot(!anyNA(d))
stopifnot(nrow(d)==32)
fit <- lm(mpg~wt,data=d)
m <- c(n=nrow(d),pearson=cor(d$wt,d$mpg),spearman=cor(d$wt,d$mpg,method="spearman"),intercept=unname(coef(fit)[1]),slope=unname(coef(fit)[2]),r_squared=summary(fit)$r.squared,p_slope=coef(summary(fit))[2,4],slope_per_lb=unname(coef(lm(mpg~I(wt*1000),data=d))[2]))
draw <- function() {plot(d$wt,d$mpg,pch=16,col=as.factor(d$cyl),xlab="Weight (1000 lb)",ylab="Miles / US gallon",main="mtcars: 32 historical models");abline(fit)}
write.csv(data.frame(metric=names(m),value=as.numeric(m)),file.path(P,"expected/r.csv"),row.names=FALSE)
png(file.path(P,"figures/result-r.png"),width=1024,height=672,res=160)
draw()
invisible(dev.off())
print(m)
