options(digits=17)
script <- sub("^--file=","",grep("^--file=",commandArgs(),value=TRUE)[1])
P <- normalizePath(file.path(dirname(script),".."),winslash="/")
for (f in c("figures","expected")) dir.create(file.path(P,f),showWarnings=FALSE)
d <- read.csv(file.path(P,"data/faithful.csv"),stringsAsFactors=FALSE)
stopifnot(!anyNA(d))
stopifnot(nrow(d)==272)
fit <- lm(waiting~eruptions,data=d)
m <- c(n=nrow(d),pearson=cor(d$eruptions,d$waiting),spearman=cor(d$eruptions,d$waiting,method="spearman"),intercept=unname(coef(fit)[1]),slope=unname(coef(fit)[2]),r_squared=summary(fit)$r.squared)
draw <- function() plot(d$eruptions,d$waiting,pch=16,col="#277d8e80",xlab="Eruption duration (min)",ylab="Waiting to next eruption (min)",main="faithful: observations, not causation")
write.csv(data.frame(metric=names(m),value=as.numeric(m)),file.path(P,"expected/r.csv"),row.names=FALSE)
png(file.path(P,"figures/result-r.png"),width=1024,height=672,res=160)
draw()
invisible(dev.off())
print(m)
